FÓRMULAS DAX
-- 1.0 - Criando a Tabela dCalendario
dCalendario = 
    VAR varDataMinFato = MIN(Realizado[Período])
    VAR varDataMaxFato = MAX(Realizado[Período])
    VAR varMesMin = MONTH(varDataMinFato)
    VAR varMesMax = MONTH(varDataMaxFato)
    VAR varAnoMin = YEAR(varDataMinFato)
    VAR varAnoMax = YEAR(varDataMaxFato)
    VAR varDataMin = DATE(varAnoMin,varMesMin,01)
    VAR varDataMax = DATE(varAnoMax,varMesMax,31)
RETURN
CALENDAR(varDataMin,varDataMax)